version: 2

# masterブランチにプッシュした場合に自動デプロイ
jobs:
  build:
    working_directory: ~/workdir
    branches:
        only:
          - maitake
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: "Nodeの依存関係のインストール(yarn)"
          command: yarn
          working_directory: App
      - run:
          name: "ReacのBuild"
          command: yarn build
          working_directory: App
      - run:
          name: "Firebaseへのデプロイ"
          command: ./node_modules/.bin/firebase deploy --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
          working_directory: App
    
